# Generated by Django 2.0.5 on 2018-05-31 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('item', models.CharField(max_length=75)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity', models.PositiveSmallIntegerField()),
                ('link', models.URLField()),
                ('approved', models.NullBooleanField()),
            ],
        ),
    ]
