# Generated by Django 2.0.5 on 2018-06-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseRequests', '0003_auto_20180531_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
