# Generated by Django 2.0.5 on 2018-06-01 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseRequests', '0004_auto_20180601_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
