# Generated by Django 2.0.5 on 2018-06-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseRequests', '0007_request_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='link',
            field=models.URLField(max_length=2000),
        ),
    ]
