# Generated by Django 2.1.3 on 2019-01-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseRequests', '0008_auto_20180618_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
