# Generated by Django 2.2.5 on 2019-09-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseRequests', '0011_request_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='supplier',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
